### PR TITLE
minimal tweaks to format as an R package

### PR DESCRIPTION
**Pull request by cboettig**
Hi @duffymeg ,

Really enjoyed your write-up on DynamicEcology of your experience in posting this code on GitHub.  Bravo!  

This pull request is more by way of me asking your opinion about this idea than really about critiquing or improving your already excellent example per se; so please feel free to ignore or close this issue.

There has been an on-going discussion (e.g. [here](https://github.com/ropensci/rrrpkg), but dates back to [Gentleman & Temple Lang 2004](http://biostats.bepress.com/bioconductor/paper2/)) as to whether or not the format of an R package is a useful, lightweight way for people to think about organizing their folders/directories for these kind of projects.  Not so the project could go on CRAN or anything, but just to pick layout that is well documented and familiar to some audience, and can allow the user to benefit from some pre-existing tools. (Nobody seems to teach about good file structure, so things can get messy pretty quickly!)

Your example is so neat and tidy that this hardly necessary; but it does make for a really nice, easy-to-understand example.  In this pull request, I've re-organized things to make this repo into a valid R package.  Basically that means putting data in `data/` directory and adding a DESCRIPTION file with some basic, machine-readable metadata about the package, such as the dependencies.  (If you have the `devtools` package installed and you do `devtools::install_github("duffymeg/BroodParasiteDescription")` R will install all the dependencies automatically.  

I did tweak the script just to avoid using an absolute path, since that will not in general be portable to other users (who won't have the same folder structure with `Box Sync/Parasites` etc).  You include the `.Rproj` file, which is great, since the working directory gets set relative to where this file lives if someone opens the project in RStudio.  Consequently, I've just defined the paths in the script all relative to that: e.g. you would run `source("analysis/CodeforBPpaper.R:)`.  Working directories are always a source of confusion, ugh.  Other than that I haven't messed with your code; but it looks very nice.  (Some people prefer that all the `library()` calls go at the top so they can easily see what packages to install first, but that's more a matter of style and is addressed in any event by listing the dependencies in the DESCRIPTION file).  

Anyway, really just curious what you think of this idea.  Thanks again for sharing your code & data, and your experience of the process!

Cheers,

Carl

### CODE REVIEW

**Comment by duffymeg** [comment]
Thanks for the comments and looking over the code! It never would have occurred to me to try to turn it into a package (because, as your comment indicated, I associate packages with things that go on CRAN). But I can see how that would help. Even though you give a clear description of creating a package, it does sound a little overwhelming to me (since I still feel just on the edge of basic competence with these sorts of things). But hopefully I will avoid laziness and give it a shot on my own next time!

**Comment by cboettig** [comment]
Thanks for your thoughts (and your tweet!)  Yup, totally agree the package format can be intimidating since it sounds like learning 'software development' instead of just whatever we already do.  

The [rrrpkg group](https://github.com/ropensci/rrrpkg) is trying to dispel that notion to some extent, pointing out that a very basic R package is really very close to what most people already do.  (e.g. no need to write functions and documentation -- just a `data/` directory for your data, an `analysis/` directory for your scripts, and a DESCRIPTION with metadata.  

My idealistic hope is that having some pre-described format actually helps people feel better about sharing code from papers in the first place. I'm all for the Nicholas Barnes perspective of "[publish your computer code, it's good enough](http://www.nature.com/news/2010/101013/full/467753a.html)", but I think that's really hard for many of us perfectionist-y types to do. It's like [being asked to take you clothes off](http://www.nature.com/news/rule-rewrite-aims-to-clean-up-scientific-software-1.17323) or something.  My hope is that by dressing code up in an accepted format like an R package, people can feel like it now has some clothes, and thus worry less about if the code is hairy underneath.

**Comment by benmarwick** [comment]
This is excellent, thanks @duffymeg and @cboettig for this wonderful example of an ultra-minimal R package. This will be very helpful for others to see how the R package structure can be useful to effectively organise and share the typical ingredients of a research project. This is also useful to dispel the notion that the only purpose of an R package is to go to CRAN (I don't have any on CRAN, and probably never will).

I love the idea of an R package as clothes to protect your modesty when baring all (of your research results), a great extension of the analogy

**Comment by noamross** [comment]
I'm a little confused as to the specific advantages of the package-level organization if there aren't functions, @cboettig.  I understand that installing it automatically installs dependencies, but doesn't installing it (1) place the actual data files in the library path (an obscure concept to many users), and (2) remove `analysis` and any other non-standard directories?

**Comment by cboettig** [comment]
Hi @noamross,

Good questions.  I believe the consensus of the rrrpkg group was that it really wasn't so important that the package installs at all (Perhaps @jennybc, @hadley or others can correct me if I've got this wrong).  The point is simply that following a consistent organizational structure is more useful than everyone inventing their own organizational structure, and makes it possible (but not required) to take advantage of certain tools (like the `devtools` functions that help create this structure automatically, or the convenience of installing the functions, etc.)

**Comment by noamross** [comment]
@cboettig I agree in general, but the changes you made primarily allow the project to be installed as a package, and there's an expectation that one should be able to interact with a package in a certain way, starting with installation.

This could be fixed if some simple information in the DESCRIPTION file (`type: Analysis-Not for Install`) changed the behavior of `devtools::install_github()` such as giving a warning ("This is a reproducible analysis package. Contains no functions. Recommend cloning the directory instead")

**Comment by jennybc** [comment]
@noamross I share some of your concerns. I was one of the more skeptical about the R package structure being the (a?) right way to structure and distribute an analysis. But I'm certainly intrigued by the proposal.

At the Unconference @gmbecker had interesting contributions about an adaptation he uses at work that extends the R package structure to this context and has room for, e.g., an "analysis" directory.

I think it is interesting and important to figure out what variant on a R package is suitable and could be installed (or whatever the right word and concept turns out to be).

**Comment by jennybc** [comment]
@duffymeg Thanks for letting us do our thing in your repo :smile:. I feel like we've set up camp in your front yard.:tent:

**Comment by duffymeg** [comment]
No problem! My (very delayed!) reply: I think, as a relative novice, creating a package seems more intimidating than working out getting the data file in a place where I can access it. So, the part about turning it into a package probably increases the (perceived) degree of difficulty, which might be a barrier.

**Comment by hadley** [comment]
@duffymeg hmmmm, I think that's a communication failure because a package should make that easier, not harder.

**Comment by duffymeg** [comment]
@hadley (and also @cboettig @jennybc and others above):
Yes, I suspect there's a communication issue here, where I am coming in without much in the way of programming experience. From my perspective, I can write the code I need in R, and, with help from twitter, managed to get it onto GitHub. Doing that this first time was pretty frustrating, until a key tweet from @pschloss got me unstuck. I feel like I can do that quickly in the future now, which is great. But hearing that I can use devtools to turn the code into a package sounds like an extra step and an extra thing to figure out. (I don't mean that to sound whiny -- just that, given limited time and programming confidence, I'm not sure whether I'd overcome the activation energy required to figure that out.) In the end, I was happy with the way things worked out with getting this code posted, but I was getting close to giving up at one point:
https://dynamicecology.wordpress.com/2015/05/28/my-first-experience-with-github-for-sharing-data-and-code/

More generally, I'm also unsure of how one would use the package. In practice, right now, what I would do is clone the repository to my computer, then update the CodeforBPpaper.R file to call the data from wherever it had been saved, and then run the rest of the code as I would normally. But I suspect that is not the way these packages are intended to be used. Is my suspicion correct?  

I'm replying in case it helps to have the novice perspective on things. Feel free to ignore! As background, I've read https://github.com/ropensci/rrrpkg but not really anything beyond that yet.

**Comment by cboettig** [comment]
@duffymeg Excellent points, thanks for sharing.  I completely agree with your observation about time to learn anything new always being a significant barrier; like you say, Git/GitHub is another good example.

I think @hadley is also on the mark about the communication failure -- I suspect my example made this look like it involves learning a lot more new stuff than it really does.  I think the basic idea is just about organization of files and doesn't have anything to do with computer savy.  The goal of organizing a set of code as a package isn't any different then your original goal of just making the code available, it's just about doing so in a tidy way.

You're original approach was already quite tidy -- you didn't need any folders because there weren't many files, right?  It wasn't perfect -- for instance, you observe that you would: 

> ... then update the CodeforBPpaper.R file to call the data from wherever it had been saved, 

the main purpose of my reorganization was simply to avoid this step one step.  As you've probably experienced, asking students to "update the code to call the data from wherever it has been saved" is a major stumbling block.  A primary goal of following the "R package" organization is to make this automatic; so a user who has cloned or downloaded the code can just type `source` or whatnot and not mess around editing code paths to find data files.  

I think one advantage of this is scale.  It's not a big deal if there aren't a lot of data files, but as projects get more complex, it's hard to keep the same organization you have here with no sub-folders.  Navigating somebody else's files and folders is always gonna be a bit tricky, but the observation of the rrrpkg discussion was that it helps if we all follow roughly the same template.  Maybe it seems overkill at this level, but I think it's nice to have a template on how to organize my files as things get more complicated.  

Like you say, maybe this is creating more problems than it solves.  You aren't the only one to ask "what do I _do_ with the package?"  Perhaps re-using the 'package' concept creates more problems then it solves, if the expectation is that being a package makes it somehow 100% more magical.  The goal wasn't to change what it can _do_, but like @hadley says, just to make it easier (getting rid of all those unspoken steps like "update the code to call the data", "install x, y, & z", "load this first", and all those other conventions we invent for ourselves).

Did that make any sense whatsoever?

**Pull request merged**
